version: "3.9"

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/motors-shop-front-end:delegated
      - /node_modules
    ports:
      - 5173:5173
    environment:
      - CHOKIDAR_USEPOLLING=true

    stdin_open: true

    command: yarn dev
